### ISSUE TITLE
Init. SSL Content

### ISSUE THREAD

**Issue by sillyo39** [Kazakuri/Shinjiru#20]
Every time I open up the application and put in my authorization code a popup appears saying: "Unable to Init ssl Content". Not sure if this has to do with me having a custom CSS on ANIList.

**Comment by Kazakuri** [comment]
Ah, thanks for the reminder.
Error initializing SSL context are caused by a few missing dlls that I've been meaning to deploy with Shinjiru.

I'm releasing 0.6.1 shortly and that should fix up all the issues.
