### ISSUE TITLE
List order doesn't sort custom lists properly

### ISSUE THREAD

**Issue by Melvinkooi** [Kazakuri/Shinjiru#25]
When sorting custom lists across the default lists (such as plan to watch, dropped etc.), the custom The custom lists are sorted at the position where the last custom list is and the way of sorting those lists ignores which custom list comes first (for example, the 2012 backlog list is not the first custom list in the section of the custom lists).

List order:
![shinjiru_2015-03-02_21-33-42](https://cloud.githubusercontent.com/assets/11279045/6450054/74b1a904-c125-11e4-804d-25c3ceb3f94d.png)
Result:
![shinjiru_2015-03-02_21-34-03](https://cloud.githubusercontent.com/assets/11279045/6450051/7068dfde-c125-11e4-9385-54ee65f1f9de.png)
Version:
![about_2015-03-02_21-38-38](https://cloud.githubusercontent.com/assets/11279045/6450046/6b466102-c125-11e4-9ae5-289a819761e7.png)

**Comment by Kazakuri** [comment]
Right now Shinjiru doesn't reorder the lists immediately after hitting the apply button. Once Shinjiru automatically reloads your list or you manually refresh using AniList > Refresh List does it display in the correct order?

**Comment by Melvinkooi** [comment]
I had refreshed it by closing the program and re-opened it and gave that result. Using the Refresh List button did give the same results.

**Comment by Kazakuri** [comment]
Ahh, okay. I see the issue.

I'll correct it soon, thanks :)

**Comment by Kazakuri** [comment]
The fix has been released in nightly update stream as of version 1.0.3 and will be available in the stable stream when version 1.1.0 is released later this week.

**Comment by Melvinkooi** [comment]
Ok, thanks for fixing it. I will test it when the fix arrives.
