### ISSUE TITLE
Season chart in Shinjiru only shows titles when added to an anime list

### ISSUE THREAD

**Issue by Melvinkooi** [Kazakuri/Shinjiru#30]
With the new version of Shinjiru (1.3.0), there's a bug in the season charts where i only can see titles of shows I've already added into my anime list.

Example season chart:
![shinjiru_2015-03-17_22-57-31](https://cloud.githubusercontent.com/assets/11279045/6698518/95be0810-ccf9-11e4-9e1e-17f7ac78f3d3.png)

Example some shows that i've added on my anime list. (see the Plastic Memories and Teen Romedy SNAFU S2 entries):
![shinjiru_2015-03-17_22-57-54](https://cloud.githubusercontent.com/assets/11279045/6698520/9d86eb34-ccf9-11e4-8f98-6fd200d915e9.png)

**Comment by Kazakuri** [comment]
Thanks a lot, the problem was related the new way anime data is loaded.
