### ISSUE TITLE
Anime List UI remains blank and "loading" when user's anime list is empty

### ISSUE THREAD

**Issue by Fugiman** [Kazakuri/Shinjiru#31]
If a user's anime list is empty, the loading bar goes into "indeterminate" state and stays there forever, and there's no indication that loading has completed.

At the very least, the loading bar should complete so the user knows the app has finished loading. Even better would be some indication that the anime list is empty and needs to be populated. Best of all might be to just kick the user over to the Browse section.

**Comment by Kazakuri** [comment]
Ah, yeah. It really should be complete, but since the list is empty, the progress bar's max value gets set to zero causing the indeterminate state.

I'll fix that up and add some sort of prompts for the user.
