### ISSUE TITLE
Watching tab merges previous state with new state after importing from MAL

### ISSUE THREAD

**Issue by iacondios** [Kazakuri/Shinjiru#36]
I fired up Shinjiru, excited to finally have a desktop updater app, and it loaded up my AniList profile splendidly. Then, I used AniList's MAL import tool to make everything up to date. To my surprise, the shows in the Watching tab that had since been completed in MAL, then imported, were not removed from the Watching tab, but merged with the new most recent watching shows. Interestingly enough, they ALSO appear in the completed tab as recorded via MAL import. Tried a couple refreshes, but they're stuck. Deleting the entry completely removes it from AniList.

Version: 1.7.3, Windows 7 Ultimate 64-bit

**Comment by Kazakuri** [comment]
Yeah, the current code for reloading lists is a bit wonky. Relaunching the application forces a complete reload and should correct those errors.

Very soon the way lists are dealt with in Shinjiru should be changing so this issue shouldn't exist for much longer.
