### ISSUE TITLE
Wrong version in the latest OsX archives

### ISSUE THREAD

**Issue by gtm87x** [Kazakuri/Shinjiru#40]
The .dmgs for 1.9.0 and 1.10.0 from the official site contain a wrong version of the program: in both of them there's the binary of version 1.8.2 instead of the expected one.

**Comment by Kazakuri** [comment]
Ah, thanks for spotting that! Silly error of mine in the build script for osx.

Should be fixed now for 1.10.0.

**Comment by gtm87x** [comment]
Yep, it's fine now. Thank you very much!
