### ISSUE TITLE
Shinjiru Set Up not working

### ISSUE THREAD

**Issue by Sakura10594** [Kazakuri/Shinjiru#45]
I downloaded the latest version on my mac (Which is running on Yosemite OS, 10.10.15) and it's downloaded fine. But when I try to open it, it always says quit unexpectedly and trying to reopen results in the same problem.

**Comment by Kazakuri** [comment]
You can't run it directly from the .dmg file (It writes to a config file, and it can't write while it's still in the archive), have you dragged it from the archive and into your apps folder (or wherever you like) ?

**Comment by Sakura10594** [comment]
*Facepalms* Worked. Thank you. I'm sorry for the stupid question, I'm still learning this mac so yeah...Thank you so much though!

**Comment by Kazakuri** [comment]
Haha, no worries. 
I don't use a Mac as my main OS either so I was confused by it at first too ^^
