### ISSUE TITLE
Add support for anime recognition in Linux

### ISSUE THREAD

**Issue by Kazakuri** [Kazakuri/Shinjiru#48]
lsof will probably work, but would have to find another solution for Crunchyroll / other streams

**Comment by Kazakuri** [comment]
Did a bit of investigation and it looks like I can use xwininfo to get info about tab titles for Firefox at least. Bit of a shame that it doesn't show vlc's title, but I can still use lsof for that.

![http://i.imgur.com/KvtpEZ7.png](http://i.imgur.com/KvtpEZ7.png)

**Comment by richese** [comment]
Try using '-tree' instead of '-children' to get all windows recursively.
[patch](https://gist.github.com/richese/8576ec80051ac1b1eedb)

**Comment by Kazakuri** [comment]
Looks good to me :+1: 

Nice work
