### ISSUE TITLE
Cannot login to anilist/change user (Linux)

### ISSUE THREAD

**Issue by Flat** [Kazakuri/Shinjiru#58]
Shinjiru thinks I'm logged in as null, upon hitting disconnect in the settings it just tries to re-login as no user. When pressing View Profile from the Anilist menu it takes me to anilist.co/user instead of an actual user link (anilist.co/user/username)

**Comment by Kazakuri** [comment]
Can you try deleting the config folder for Shinjiru inside `~/.config/` to see if that fixes things up?

Unfortunately I won't be able to access a Linux VM until tomorrow, but I expect the disconnect button isn't properly clearing the configuration values for you.

**Comment by Flat** [comment]
Looks like that worked and brought up the login page on next launch. Oddly enough though this was a first time install and I've never used it before. Unsure why it wouldn't have worked the first time but the second was fine.

**Comment by Kazakuri** [comment]
Yeah, that's really weird, I'm glad it was a simple fix for you though.

I'll still try and play with it tomorrow to see if I can figure out why it did that. Enjoy!
